# Generated by Django 4.2 on 2023-04-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_doctor_user_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
