# Generated by Django 4.2 on 2023-04-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_appointment_access_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='access_id',
            field=models.CharField(default=0, max_length=190),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='health_notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='card_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='matric',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
